### ISSUE TITLE
Turn down default sounds

### ISSUE THREAD

**Issue by pyskaa0506** [Quit975/DuckyGame#17]
Default music is too loud

**Comment by Quit975** [comment]
So music or sounds? :D

**Comment by zielonoludek** [comment]
Could we add the option to stop music? It's so annoying to hear it all the time during testing.
e.g. Press M to stop music?

**Comment by Quit975** [comment]
> 

Good idea, BUT as a challenge let's do it in a way that it works only in debug versions (debug and qa). The player playing the release version should not have this option :)

**Comment by zielonoludek** [comment]
Deal ^^

**Comment by Quit975** [comment]
Ok, to deal with this you first need to:
1. Create a public function in our MusicPlayer that will toggle the sf::Music on/off ([here ](https://www.sfml-dev.org/documentation/2.5.1/classsf_1_1Music.php)you will find sf::Music documentation)
2. In the main game loop, where we poll window events, react to the KeyReleased event (check the KeyPressed and KeyReleased section [here ](https://www.sfml-dev.org/tutorials/2.5/window-events.php)to see how)
3. When reacting to that event, simply call the function created in step 1, here is a pseudocode
```
if(event.type == KeyReleased && event.key == Keyboard::M)
{
 music.Toggle();
}
```

4. To make it do nothing in Release, you can simply wrap the implementation of the Toggle() function into #ifndef, like so
```
void MusicPlayer::Toggle()
{
#ifndef _RELEASE
// here goes your code
#endif
} 
```
Thanks to that, the function will be empty in release, and the compiler will optimize it away (it won't be called at all). It's not a good solution though, because someone might look at Toggle and think that it's a valid function to use (which is totally sensible). So instead, you can wrap the code written in point 3 into ifndef, it will be much better, cleaner solution, and the Toggle() function will remain useful in case we will want to have some options in the future where the player can disable music
