### ISSUE TITLE
Player and enemies are too fast

### ISSUE THREAD

**Issue by zielonoludek** [Quit975/DuckyGame#24]

**Comment by Quit975** [comment]
It's actually a bug, i think @Ania000 and @ArcherWike were already investigating it? The problem is that the game renders frames as fast as the computer it runs on allows, disregarding how long it actually took to render a frame. 
To fix that, the game needs to:
1. keep the game at constant fps (probably 60)
2. take the delta time (how long it took to render the frame) into consideration when updating the state of the game

**Comment by Quit975** [comment]
If it's open, it shouldn't be in Done on the board 😄
