### ISSUE TITLE
Add pause feature

### ISSUE THREAD

**Issue by Daria13szamman** [Quit975/DuckyGame#33]
For example pressing "P" key, for pause?

**Comment by Quit975** [comment]
Ok, but maybe let's use Esc key instead. Later on, we will probably need to add "are you sure" prompt but that's a different issue for a different milestone

**Comment by zielonoludek** [comment]
I would use esc key as 'quit game', maybe it's good idea for new issue?

**Comment by Quit975** [comment]
Yeah, one of the missing basic features is the ability to close the game "normally". For now esc just pausing the game will be fine and we can create a new issue about quitting the game.

**Comment by Quit975** [comment]
Couple of tips how to easily achieve this

1. in Main.cpp, line 20, we have our main game loop. In order to pause the game, we simply need to suspend it, specifically the three calls to scene in 33. In order to unpause, we need to resume their execution
2. To do that, you can have a bool flag that will be checked when calling scenes, for example
```
if(!isPaused)
{
    scene.Update(dt);
    scene.CheckCollisions();
    scene.Draw();
}
```
You can enable/disable it by reacting to a KeyReleased event in the event loop in 27. This article will explain everything you need
https://www.sfml-dev.org/tutorials/2.5/window-events.php

3. A very easy way to toggle a bool value is to simply assign it's negation to itself :)
```
isPaused = !isPaused;
```
4. And I think that's it :D any questions let us know, via Q&A or DC
