### ISSUE TITLE
Green enemies attack the player without touching them.

### ISSUE THREAD

**Issue by Daria13szamman** [Quit975/DuckyGame#46]
Green enemies sometimes attack the player, even if the player didn't touch them. Especially when the player is moving and the green enemy moves beside the player. Enemy doesn't touch the player but the quack count goes up.

**Comment by Quit975** [comment]
Great, great find :) Was wondering if someone notices that :D will talk about it more during the meeting

**Comment by Quit975** [comment]
The problem is as discussed - rotating square enemy cases the bounding box to increase in its area. We need a way to represent collision much more closely to the actual visuals

**Comment by Quit975** [comment]
Ok, for now let's solve this using the approach similar to player - every entity should have a Circle based collision (instead of using their sprite's bounds), and let's not check collisions against bounds but rather by making the calculation ourselves (the sum of the radii should be smaller than the length of the vector between two tested entities)
